### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [MrDandycorn/vk-botting#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.8.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary vk-botting -w /tmp/ext vk-botting==0.8.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting vk-botting==0.8.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/e18/2b4b142ba5dd7/vk-botting-0.8.5.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-t6pz0pld/vk-botting/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-t6pz0pld/vk-botting/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-t6pz0pld/vk-botting/pip-egg-info
         cwd: /tmp/pip-wheel-t6pz0pld/vk-botting/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-t6pz0pld/vk-botting/setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by MrDandycorn** [comment]
Thanks for pointing this out. Fixed in 0.8.6
